version: '3.8'
networks:
  economy-net:
    driver: bridge

services:
  backend:
    build:
      context: ./api
    image: economy-api:${BACKEND_TAG}
    ports:
      - "5001:5001"
    env_file:
      - ./.env
    volumes:
      - ./api:/app:Z #rw
      #- ./database/sqlite:/app/db:Z #rw  # Bind mount para SQLite
    working_dir: /app
    #command: python -m flask run --host=0.0.0.0 --port=5001 --reload --debug
    #command: flask run --host=0.0.0.0 --port=5001 --reload #--extra-files /app/app.py
    #command: flask --app app.py run --host=0.0.0.0 --port=5001 --reload
    command: python app.py
    networks:
      - economy-net

  frontend:
    build:
      context: ./client
    image: economy-client:${FRONTEND_TAG}
    ports:
      - "4200:4200"
    env_file:
      - ./.env
    volumes:
      - ./client:/app:rw
    working_dir: /app
    #command: npx ng serve --host 0.0.0.0 --port 4200
    command: npx ng serve --host 0.0.0.0 --port 4200
    depends_on:
      - backend
    networks:
      - economy-net
  ai:
    image: ghcr.io/ggml-org/llama.cpp:server-b8067
    container_name: economy-ai
    ports:
      - "8181:8180"
    volumes:
      - ./models:/models:Z
    command:
      --model /models/qwen2.5-1.5b-instruct-q4_k_m.gguf
      --host 0.0.0.0
      --port 8180
      --threads 6
      --ctx-size 2048
      --batch-size 512
    networks:
      - economy-net
  postgres:
    image: postgres:18
    container_name: economy_db
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - ./database/postgres:/var/lib/postgresql:Z

    networks:
      - economy-net
